### ISSUE TITLE
UNRAR does not appear to be installed in the image

### ISSUE THREAD

**Issue by riddlecp** [hotio/docker-mylar3#2]
When using any task that might need to open the file and extract portions I'm getting 500 errors.  The on-system log says that unrar might not be installed and when you try to view a comic in the browser you get a full stack trace:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/lib/rarfile/rarfile.py", line 2869, in custom_popen
    p = Popen(cmd, bufsize=0, stdout=PIPE, stdin=PIPE, stderr=STDOUT,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'unrar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar/webserve.py", line 6779, in read_comic
    data = wv.read_comic(ish_id, page_num, size)
  File "/app/mylar/webviewer.py", line 74, in read_comic
    scanner.user_unpack_comic(ish_id, comic_path)
  File "/app/mylar/webviewer.py", line 142, in user_unpack_comic
    opened_rar.extractall(os.path.join(mylar.CONFIG.CACHE_DIR, "webviewer", ish_id))
  File "/app/lib/rarfile/rarfile.py", line 829, in extractall
    self._extract(fnlist, path, pwd)
  File "/app/lib/rarfile/rarfile.py", line 894, in _extract
    p = custom_popen(cmd)
  File "/app/lib/rarfile/rarfile.py", line 2873, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
lib.rarfile.rarfile.RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
Powered by CherryPy 18.6.0

**Comment by hotio** [comment]
should be fixed when the build is done
